---
- name: Deploy java docs
  hosts: beetroot
  remote_user: ansible

  vars:
    java_doc_base_dir: "/data/javadocs"
    gradle_project_name: "{{ gradle_project_name }}"
    gradle_project_version: "{{ gradle_project_version }}"
    java_doc_temp_dir: "{{ java_doc_temp_dir }}"

  tasks:
#    - name: Remove directory if exists
#      ansible.builtin.file:
#        path: "{{ java_doc_base_dir }}/{{ gradle_project_name }}/{{ gradle_project_version }}"
#        state: absent
    - name: Create directory for JavaDoc
      ansible.builtin.file:
        path: "{{ java_doc_base_dir }}/{{ gradle_project_name }}/{{ gradle_project_version }}"
        state: directory
        mode: "0755"
    - name: Copy JavaDoc files to new directory
      ansible.builtin.copy:
        src: "{{ java_doc_temp_dir }}"
        dest: "{{ java_doc_base_dir }}/{{ gradle_project_name }}/{{ gradle_project_version }}"
        mode: "0644"
        directory_mode: "0755"
      with_fileglob:
        - "build/docs/javadoc/*"
    - name: Unlink old latest link
      ansible.builtin.command:
        cmd: "cd {{ java_doc_base_dir }}/{{ gradle_project_name }} && unlink latest"
      changed_when: false
    - name: Link new latest
      ansible.builtin.command:
        cmd: "cd {{ java_doc_base_dir }}/{{ gradle_project_name }} && ln -s {{ gradle_project_version }} latest"
      changed_when: false
